feat: fix Brazil phone numbers before placing the call
FossifyOrg/Phone pull request #289
Opened 2024-12-24 16:14 UTC by afarah1

#### What is it?
- [ ] Bugfix
- [x] Feature
- [ ] Codebase improvement

#### Description of the changes in your PR

This PR adds a feature *disabled by default* that fixes Brazil phone numbers before placing the call.

**Why?** Brazil added a 9 before all existing mobile numbers a couple years ago. Calls that do not include the "new" leading 9 fail. This is particularly annoying because, besides having to edit all your contacts, a lot of numbers advertised online still miss the 9, so if you click to call, the call fails. This feature recognizes it's a Brazil phone number without the 9 and adapts the number on the fly.

**Why just Brazil?** The feature is implemented in a generic way such that new country-specific rules can easily be plugged in the future. I think Italy has a similar use case with leading zeroes. If or when new countries are supported the setting text can be changed from "fix Brazil phone numbers" to "fix phone numbers" or something like that.

**Why not use a library**? I considered using [Google's libphonenumber](https://github.com/google/libphonenumber) for this, but it does not support formatting Brazil mobile numbers, nor does it allow modifying a `PhoneNumber`, which is necessary for this feature: although we can use `setNationalNumber` to modify a `PhoneNumber` and `formatInOriginalFormat` to get it back in the original format, the latter falls back to the (unmodified) raw input if the formated phone number differs from it (see [here](https://github.com/google/libphonenumber/blob/master/java/libphonenumber/src/com/google/i18n/phonenumbers/PhoneNumberUtil.java#L1746)). Since we modified the `PhoneNumber` adding the `9`, it just removes it back. We could also modify the `rawInput` but that means dealing with raw strings and if so we don't need the lib (which is what we end up doing). There are [other issues](https://stackoverflow.com/questions/52520013/libphonenumber-formatting-phone-numbers-without-knowing-the-country-code) with this library that make it not very suitable for our purposes. It would also add a new non-trivial dependency to the project. You can check [a branch in my fork](https://github.com/afarah1/Phone/commit/26b300a643022dc8ecaeaa60385c36e08cdb5848) with an attempt at using libphonenumber, but some very essential test cases fail. I considered alternatives but did not find any suitable one.

I note that a shortcoming of not using `libphonenumber` is that the following numbers do not get fixed:

1. IDD calls (country-specific international calling made without +COUNTRY_CODE)
2. RFC 3966 extensions (like `tel:863-1234;phone-context=+1-914-555`)
3. Non-digit numbers (like `1-800-Flowers` or `*555`)

I think this is an acceptable trade-off because those are not the numbers we are aiming to fix nor does one usually dial with phone extensions or IDD.

I ran several test cases, everything is inside a `try catch` block, _and_ the feature is disabled by default, so I think it's pretty safe.

The project did not have any unit tests, I took the liberty to add some for the new feature, which adds some dev dependencies.

PS: I'm assuming Android API 23+ for [`getSystemService` with the class](https://developer.android.com/reference/android/content/Context#getSystemService(java.lang.Class%3CT%3E)) (Android 6+, [97,9% adoption](https://apilevels.com/)).

I'm not a mobile developer so please let me know of any issues and I can amend. I couldn't auto-format the code in vscode, I tried my best to format it manually, feel free to commit a patch if needed.

Besides the unit tests I ran tests on a physical Galaxy A14 with Android 14, see below for details.

<details>
<summary><b>Tests and evidence</b></summary>

I tested with real numbers, but for the sake of privacy I re-tested with a fake number.

## From contacts

### Old number w/o country code

```
12-24 11:57:35.186 13902 13902 D CallNumberHelper: Iso: BR
12-24 11:57:35.186 13902 13902 D CallNumberHelper: Brazil phone: 90000000
12-24 11:57:35.186 13902 13902 D CallNumberHelper: Brazil fixed phone: 990000000
```

<img alt="old-contacts" src="https://github.com/user-attachments/assets/90796cfb-c971-4fa7-beb3-bb8dc195f851" width=179 />

## From dialpad

### Old number w/o country code

```
12-24 11:59:26.082 13902 13902 D CallNumberHelper: Iso: BR
12-24 11:59:26.082 13902 13902 D CallNumberHelper: Brazil phone: 80000000
12-24 11:59:26.082 13902 13902 D CallNumberHelper: Brazil fixed phone: 980000000
```

<img alt="old-dialpad" src="https://github.com/user-attachments/assets/b612ada1-8358-40c1-bc49-30f4be7815e0" width=179 />

### New number w/o country code

```
12-24 12:01:58.176 13902 13902 D CallNumberHelper: Iso: BR
12-24 12:01:58.176 13902 13902 D CallNumberHelper: Brazil phone: 980000000
```

### Old number w/ country code

```
12-24 12:02:37.079 13902 13902 D CallNumberHelper: Code: 55
12-24 12:02:37.080 13902 13902 D CallNumberHelper: Brazil phone: +5580000000
12-24 12:02:37.080 13902 13902 D CallNumberHelper: Brazil fixed phone: +55980000000
```

### Land number

```
12-24 12:02:55.518 13902 13902 D CallNumberHelper: Iso: BR
12-24 12:02:55.518 13902 13902 D CallNumberHelper: Brazil phone: 30000000
```

### Non supported country

```
12-24 12:03:23.768 13902 13902 D CallNumberHelper: Code: 18
```

## Setting

I tested that with the setting disabled does not change the number.

</details>

----

#### Before/After Screenshots/Screen Record
- Before:

<img alt="before" src="https://github.com/user-attachments/assets/ee7ed228-6633-4f3e-a484-9043c0cc24ee" width=179 />

- After:

<img alt="after" src="https://github.com/user-attachments/assets/fcf0f406-821e-492d-8fe0-346999b8917e" width=179 />

#### Acknowledgement
- [x] I read the [contribution guidelines](https://github.com/FossifyOrg/Phone/blob/master/CONTRIBUTING.md).

2024-12-24 17:07 UTC, Aga-C commented
Thanks for contributing, but next time please create an issue or discussion first (as stated in the contribution guidelines).

Also, why have you added it as an option? I think it's not needed to be optional, as it only affects wrongly stored/typed Brazilian numbers.

2025-01-21 13:08 UTC, naveensingh commented
Not really, I'll review it later.

2025-03-15 15:04 UTC, naveensingh commented
I know this is not a high-risk change but I still have some questions.

> This feature recognizes it's a Brazil phone number without the 9 and adapts the number on the fly.

Are there any Phone or Dialer apps that do this?

> This is particularly annoying because, besides having to edit all your contacts

Aren't there apps (e.g. Novo Dígito BR) for this? Why not use those?

> a lot of numbers advertised online still miss the 9, so if you click to call, the call fails

Those usually lead users to a dialpad so one could easily insert the 9th digit and with time, I'm guessing this will be happening less and less.

> Brazil added a 9 before all existing mobile numbers a couple years ago. Calls that do not include the "new" leading 9 fail. This is particularly annoying because, besides having to edit all your contacts, a lot of numbers advertised online still miss the 9, so if you click to call, the call fails.

If automatically adding the ninth digit is "safe" i.e. without unintended consequences, any guesses why ANATEL didn't make it mandatory for telecom providers to implement this change when they standardized it?

2025-03-15 15:08 UTC, naveensingh requested changes

2025-03-15 15:08 UTC, naveensingh commented on app/build.gradle.kts
> +    testImplementation("org.robolectric:robolectric:4.14")
Use [version catalogs](https://docs.gradle.org/current/userguide/version_catalogs.html) please.

2025-03-15 15:08 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/countries/Brazil.kt
> +	return ' '
Couldn't this be just `null`?

2025-03-15 15:08 UTC, naveensingh commented on app/src/test/kotlin/org/fossify/phone/helpers/CallNumberHelperTestBrazil.kt
> +	fun testlLandLocalAreaNumber() {
Minor typo:

```suggestion
	fun testLandLocalAreaNumber() {
```

2025-03-23 13:48 UTC, afarah1 commented on app/build.gradle.kts
> +    testImplementation("org.robolectric:robolectric:4.14")
Done in a new commit.

2025-03-23 13:49 UTC, afarah1 commented on app/src/main/kotlin/org/fossify/phone/helpers/countries/Brazil.kt
> +	return ' '
Just changing for `null` yields a compile error (Null can not be a value of a non-null type Char). Not sure if changing the return type to something else would be desirable.

2025-03-23 14:03 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/countries/Brazil.kt
> +	return ' '
Kotlin is explicit that way. See https://kotlinlang.org/docs/null-safety.html#nullable-types-and-non-nullable-types

The nullable return type will be `Char?`

2025-04-01 12:57 UTC, closed without merging