Additional language on dialpad
FossifyOrg/Phone pull request #49
Opened 2024-01-21 19:41 UTC by Belyavin

Fixes FossifyOrg/Phone#47

2024-01-21 20:00 UTC, Aga-C commented on app/src/main/res/values/strings.xml
> +    <string name="none_explicit">none</string>
Instead of creating a new string, please use `none` from Commons.

2024-01-21 20:07 UTC, Aga-C commented
Letters in both languages should be centered (e.g. 3 looks really bad).

![image](https://github.com/FossifyOrg/Phone/assets/85929121/9b266842-6ac5-4219-aca4-3c90c3844766)

2024-01-22 21:53 UTC, derrohrbach commented
@Aga-C also the height of the lowest row of keys is different, which looks weird. 

And also # and * are not vertically aligned with the 0, but this is also the case on the master branch. Might be a different PR?

2024-01-23 19:14 UTC, Belyavin commented
I've changed the string to a common one, and aligned the text to the center. I also aligned * and # to 0, though I'm not sure if it became better, need you opinion on this.

2024-01-23 19:16 UTC, Belyavin commented
![New text alignment](https://github.com/FossifyOrg/Phone/assets/154713931/045f073c-a47e-41d1-b58e-dd296d13fe4d)

2024-02-05 10:26 UTC, HenriDellal requested changes

2024-02-05 10:26 UTC, HenriDellal commented on app/src/main/res/raw/t9languages.json
> +            "ЭЬЮЯ"
```suggestion
            "ЬЭЮЯ"
```

2024-02-23 12:31 UTC, Belyavin commented
Hi, are we waiting for something before merging?

2024-02-23 13:07 UTC, Aga-C commented
@Belyavin You have to wait for the final review from Naveen.

2024-03-18 00:14 UTC, naveensingh commented on app/src/main/res/layout/activity_settings.xml
> +
This is still referencing the deleted `none_explicit` string.

2024-03-18 01:27 UTC, naveensingh requested changes

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/activities/SettingsActivity.kt
> +        }
Duplicated code from `setupFontSize()`

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/DialpadT9.kt
> +        public val charMap = CharMap()
Redundant `public` modifier.

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/DialpadT9.kt
> +    public var Initialized = false
The variable name should start with a lowercase letter. Another redundant `public` modifier.

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/DialpadT9.kt
> +        Initialized = true;
Useless `;`

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/DialpadT9.kt
> +            else if (langEn != null && langEn.charMap.containsKey(c)) {
The code in `DialpadT9.kt` isn't properly formatted in many places. 

https://stackoverflow.com/questions/16580171/code-formatting-shortcuts-in-android-studio-for-operation-systems

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/DialpadT9.kt
> +            if(number in 2..9) {
There is no space between `if` and `(`...

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/kotlin/org/fossify/phone/helpers/DialpadT9.kt
> +    public fun readFromJson(jsonText: String){
There is no space between `)` and `{`...

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/res/layout/dialpad.xml
>              android:layout_below="@+id/dialpad_2"
The attribute `android:layout_below` is not valid in the `LinearLayout`. It's there in every button from `dialpad_2_holder` to `dialpad_0_holder` except the asterisk.

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/res/layout/dialpad.xml
>              android:layout_centerInParent="true"
`android:layout_centerInParent="true"` is not valid in the LinearLayout.

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/res/layout/dialpad.xml
>              android:layout_centerInParent="true"
`android:layout_centerInParent="true"` is not valid in the LinearLayout.

2024-03-18 01:27 UTC, naveensingh commented on app/src/main/res/layout/dialpad.xml
>              android:layout_centerInParent="true"
`android:layout_centerInParent="true"` is not valid in the LinearLayout.

2024-03-18 01:31 UTC, naveensingh commented
> I also aligned * and # to 0, though I'm not sure if it became better, need you opinion on this.

@Belyavin indeed * and # look better when centered, I reverted that change.

2024-09-25 18:16 UTC, closed without merging